src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Models/Layout/FooterViewModel.cs
using MyCompanyName.AbpZeroTemplate.Sessions.Dto;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout
{
    public class FooterViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public string GetProductNameWithEdition()
        {
            var productName = "AbpZeroTemplate";

            if (LoginInformations.Tenant != null && LoginInformations.Tenant.EditionDisplayName != null)
            {
                productName += " " + LoginInformations.Tenant.EditionDisplayName;
            }

            return productName;
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Localization;
using MyCompanyName.AbpZeroTemplate.Sessions.Dto;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }

        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public bool IsImpersonatedLogin { get; set; }

        public string GetShownLoginName()
        {
            var userName = "<span id=\"HeaderCurrentUserName\">" + LoginInformations.User.UserName + "</span>";

            if (!IsMultiTenancyEnabled)
            {
                return userName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + userName
                : LoginInformations.Tenant.TenancyName + "\\" + userName;
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Models/Layout/SidebarViewModel.cs
using Abp.Application.Navigation;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout
{
    public class SidebarViewModel
    {
        public UserMenu Menu { get; set; }

        public string CurrentPageName { get; set; }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Models/Layout/HeaderViewModel.cs
using System.Collections.Generic;
using Abp.Application.Navigation;
using Abp.Localization;
using MyCompanyName.AbpZeroTemplate.Sessions.Dto;

namespace MyCompanyName.AbpZeroTemplate.Web.Models.Layout
{
    public class HeaderViewModel
    {
        public GetCurrentLoginInformationsOutput LoginInformations { get; set; }
        
        public IReadOnlyList<LanguageInfo> Languages { get; set; }

        public LanguageInfo CurrentLanguage { get; set; }
        
        public UserMenu Menu { get; set; }
        
        public string CurrentPageName { get; set; }

        public bool IsMultiTenancyEnabled { get; set; }

        public string GetShownLoginName()
        {
            if (!IsMultiTenancyEnabled)
            {
                return LoginInformations.User.UserName;
            }

            return LoginInformations.Tenant == null
                ? ".\\" + LoginInformations.User.UserName
                : LoginInformations.Tenant.TenancyName + "\\" + LoginInformations.User.UserName;
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Threading;
using Abp.Web.Mvc.Authorization;
using MyCompanyName.AbpZeroTemplate.Authorization.Users;
using MyCompanyName.AbpZeroTemplate.Sessions;
using MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout;
using MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Startup;
using MyCompanyName.AbpZeroTemplate.Web.Controllers;

namespace MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Controllers
{
    [AbpMvcAuthorize]
    public class LayoutController : AbpZeroTemplateControllerBase
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public LayoutController(
            ISessionAppService sessionAppService, 
            IUserNavigationManager userNavigationManager, 
            IMultiTenancyConfig multiTenancyConfig, 
            IUserLinkAppService userLinkAppService)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
        }

        [ChildActionOnly]
        public PartialViewResult Header()
        {
            var headerModel = new HeaderViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations()),
                Languages = LocalizationManager.GetAllLanguages(),
                CurrentLanguage = LocalizationManager.CurrentLanguage,
                IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled,
                IsImpersonatedLogin = AbpSession.ImpersonatorUserId.HasValue
            };

            return PartialView("_Header", headerModel);
        }

        [ChildActionOnly]
        public PartialViewResult Sidebar(string currentPageName = "")
        {
            var sidebarModel = new SidebarViewModel
            {
                Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(MpaNavigationProvider.MenuName, AbpSession.UserId)),
                CurrentPageName = currentPageName
            };

            return PartialView("_Sidebar", sidebarModel);
        }

        [ChildActionOnly]
        public PartialViewResult Footer()
        {
            var footerModel = new FooterViewModel
            {
                LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations())
            };

            return PartialView("_Footer", footerModel);
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Controllers/LayoutController.cs
using System.Web.Mvc;
using Abp.Application.Navigation;
using Abp.Configuration.Startup;
using Abp.Threading;
using MyCompanyName.AbpZeroTemplate.Sessions;
using MyCompanyName.AbpZeroTemplate.Web.Models.Layout;
using MyCompanyName.AbpZeroTemplate.Web.Navigation;

namespace MyCompanyName.AbpZeroTemplate.Web.Controllers
{
    /// <summary>
    /// Layout for 'front end' pages.
    /// </summary>
    public class LayoutController : AbpZeroTemplateControllerBase
    {
        private readonly ISessionAppService _sessionAppService;
        private readonly IUserNavigationManager _userNavigationManager;
        private readonly IMultiTenancyConfig _multiTenancyConfig;

        public LayoutController(ISessionAppService sessionAppService, IUserNavigationManager userNavigationManager, IMultiTenancyConfig multiTenancyConfig)
        {
            _sessionAppService = sessionAppService;
            _userNavigationManager = userNavigationManager;
            _multiTenancyConfig = multiTenancyConfig;
        }

        [ChildActionOnly]
        public PartialViewResult Header(string currentPageName = "")
        {
            var headerModel = new HeaderViewModel();
            
            if (AbpSession.UserId.HasValue)
            {
                headerModel.LoginInformations = AsyncHelper.RunSync(() => _sessionAppService.GetCurrentLoginInformations());
            }

            headerModel.Languages = LocalizationManager.GetAllLanguages();
            headerModel.CurrentLanguage = LocalizationManager.CurrentLanguage;
            headerModel.Menu = AsyncHelper.RunSync(() => _userNavigationManager.GetMenuAsync(FrontEndNavigationProvider.MenuName, AbpSession.UserId));
            headerModel.CurrentPageName = currentPageName;

            headerModel.IsMultiTenancyEnabled = _multiTenancyConfig.IsEnabled;

            return PartialView("~/Views/Layout/_Header.cshtml", headerModel);
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Controllers/ProfileController.cs
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Abp.Auditing;
using Abp.Domain.Uow;
using Abp.Extensions;
using Abp.IO.Extensions;
using Abp.Runtime.Session;
using Abp.UI;
using Abp.Web.Models;
using Abp.Web.Mvc.Authorization;
using Abp.Web.Mvc.Models;
using MyCompanyName.AbpZeroTemplate.Authorization.Users;
using MyCompanyName.AbpZeroTemplate.Net.MimeTypes;
using MyCompanyName.AbpZeroTemplate.Storage;

namespace MyCompanyName.AbpZeroTemplate.Web.Controllers
{
    [AbpMvcAuthorize]
    public class ProfileController : AbpZeroTemplateControllerBase
    {
        private readonly UserManager _userManager;
        private readonly IBinaryObjectManager _binaryObjectManager;

        public ProfileController(UserManager userManager, IBinaryObjectManager binaryObjectManager)
        {
            _userManager = userManager;
            _binaryObjectManager = binaryObjectManager;
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePicture()
        {
            var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());
            if (user.ProfilePictureId == null)
            {
                return GetDefaultProfilePicture();
            }

            return await GetProfilePictureById(user.ProfilePictureId.Value);
        }

        [DisableAuditing]
        public async Task<FileResult> GetProfilePictureById(string id = "")
        {
            if (id.IsNullOrEmpty())
            {
                return GetDefaultProfilePicture();                
            }

            return await GetProfilePictureById(Guid.Parse(id));
        }

        [UnitOfWork]
        public async virtual Task<JsonResult> ChangeProfilePicture()
        {
            try
            {
                //Check input
                if (Request.Files.Count <= 0 || Request.Files[0] == null)
                {
                    throw new UserFriendlyException(L("ProfilePicture_Change_Error"));
                }

                var file = Request.Files[0];

                if (file.ContentLength > 30720) //30KB.
                {
                    throw new UserFriendlyException(L("ProfilePicture_Warn_SizeLimit"));
                }

                //Get user
                var user = await _userManager.GetUserByIdAsync(AbpSession.GetUserId());

                //Delete old picture
                if (user.ProfilePictureId.HasValue)
                {
                    await _binaryObjectManager.DeleteAsync(user.ProfilePictureId.Value);
                }

                //Save new picture
                var storedFile = new BinaryObject(file.InputStream.GetAllBytes());
                await _binaryObjectManager.SaveAsync(storedFile);

                //Update new picture on the user
                user.ProfilePictureId = storedFile.Id;

                //Return success
                return Json(new MvcAjaxResponse());
            }
            catch (UserFriendlyException ex)
            {
                //Return error message
                return Json(new MvcAjaxResponse(new ErrorInfo(ex.Message)));
            }
        }

        private FileResult GetDefaultProfilePicture()
        {
            return File(Server.MapPath("~/Common/Images/default-profile-picture.png"), MimeTypeNames.ImagePng);
        }

        private async Task<FileResult> GetProfilePictureById(Guid profilePictureId)
        {
            var file = await _binaryObjectManager.GetOrNullAsync(profilePictureId);
            if (file == null)
            {
                return GetDefaultProfilePicture();
            }

            return File(file.Bytes, MimeTypeNames.ImageJpeg);
        }
    }
}

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Views/Layout/_Footer.cshtml
@using MyCompanyName.AbpZeroTemplate
@model MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout.FooterViewModel
    @{
        Layout = null;
    }
    <div class="page-footer-inner">
        <span class="text-muted">
            <small>
                @Model.GetProductNameWithEdition() <br/>
                v@(AppVersionHelper.Version) [@AppVersionHelper.ReleaseDate.ToString("yyyyMMdd")]
            </small>
        </span>
    </div>
    <div class="scroll-to-top">
        <i class="icon-arrow-up"></i>
    </div>

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Views/Layout/_Header.cshtml
@using Abp.Timing
@model MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout.HeaderViewModel
@{
    Layout = null;
}
<div class="page-header-inner">
    <div class="page-logo">
        <a href="@Url.Action("Index", "Home", new {area = string.Empty})" target="_blank">
            <img src="~/Common/Images/app-logo-on-light.png" alt="logo" class="logo-default" width="168" height="33" />
        </a>
        <div class="menu-toggler sidebar-toggler">
            <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
        </div>
    </div>
    <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
    </a>
    <div class="page-top">
        <div class="top-menu">
            <ul class="nav navbar-nav pull-right">
                @if (Model.Languages.Count > 1)
                {
                    <li class="dropdown dropdown-language">
                        <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                            <i class="@Model.CurrentLanguage.Icon"></i>
                            <span class="langname">
                                @Model.CurrentLanguage.DisplayName
                            </span>
                            <i class="fa fa-angle-down"></i>
                        </a>
                        <ul class="dropdown-menu">
                            @foreach (var language in Model.Languages.Where(language => language.Name != Model.CurrentLanguage.Name))
                            {
                                <li>
                                    <a href="~/AbpLocalization/ChangeCulture?cultureName=@language.Name&returnUrl=@Request.Url" href="#">
                                        <i class="@language.Icon"></i> @language.DisplayName
                                    </a>
                                </li>
                            }
                        </ul>
                    </li>
                }

                <!-- BEGIN NOTIFICATION DROPDOWN -->
                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-extended dropdown-notification dropdown-dark" id="header_notification_bar">

                </li>
                <!-- END NOTIFICATION DROPDOWN -->
                <li class="separator hide"> </li>

                <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
                <li class="dropdown dropdown-user dropdown-dark">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" title="@(Model.IsImpersonatedLogin ? L("YouCanBackToYourAccount") : "")">
                        <span class="username username-hide-on-mobile">
                            @if (Model.IsImpersonatedLogin)
                            {
                                <i class="icon-action-undo font-red-sunglo"></i>
                            }
                            @Html.Raw(Model.GetShownLoginName())
                        </span>
                        <img id="HeaderProfilePicture" alt="" class="img-circle" src="@Url.Action("GetProfilePicture", "Profile", new {area = string.Empty})?t=@Clock.Now.Ticks.ToString()" />
                    </a>
                    <ul class="dropdown-menu dropdown-menu-default">
                        @if (Model.IsImpersonatedLogin)
                        {
                            <li>
                                <a id="UserProfileBackToMyAccountButton" href="#"><i class="icon-action-undo"></i> <strong>@L("BackToMyAccount")</strong></a>
                            </li>
                            <li class="divider"></li>
                        }
                        <li class="dropdown-submenu">
                            <a class="open-left" href=""><i class="icon-link"></i> @L("LinkedAccounts")</a>
                            <ul id="RecentlyUsedLinkedUsers" class="dropdown-menu" style=""></ul>
                        </li>
                        <li>
                            <a id="UserProfileChangePasswordLink" href="#"><i class="icon-key"></i> @L("ChangePassword")</a>
                        </li>
                        <li>
                            <a id="UserProfileChangePictureLink" href="#"><i class="icon-user"></i> @L("ChangeProfilePicture")</a>
                        </li>
                        <li>
                            <a id="UserProfileMySettingsLink" href="#"><i class="icon-settings"></i> @L("MySettings")</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="@Url.Action("Logout", "Account", new {area = string.Empty})"><i class="icon-logout"></i> @L("Logout")</a>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>
<script id="linkedAccountsSubMenuTemplate" type="x-tmpl-mustache">
    {{#items}}
    <li>
        <a href="" data-user-id="{{id}}" class="recently-linked-user">
            <img src="{{profilePictureUrl}}" width="22" height="22" class="img-rounded" />
            {{shownUserName}}
        </a>
    </li>
    {{/items}}
    {{#hasLinkedUsers}}
    <li class="divider"></li>
    {{/hasLinkedUsers}}
    <li>
        <a href="" id="ManageLinkedAccountsLink">
            <i class="icon-settings"></i> @L("ManageAccounts")
        </a>
    </li>
</script>
<script id="headerNotificationBarTemplate" type="x-tmpl-mustache">
    <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
        <i class="icon-bell"></i>
        {{#unreadCount}}
        <span class="badge badge-danger"> {{unreadCount}} </span>
        {{/unreadCount}}
    </a>
    <ul class="dropdown-menu" id="UserNotificationDropdown">
        <li class="external notifications-header">
            <div class="text-left">
                {{#unreadCount}}
                <a href="" id="setAllNotificationsAsReadLink">@L("SetAllAsRead")</a>
                {{/unreadCount}}
                <a id="openNotificationSettingsModalLink" class="pull-right" href="">@L("Settings")</a>
            </div>
        </li>
        <li>
            <ul class="dropdown-menu-list">
                {{#notifications}}
                <li>
                    <a href="{{url}}" class="user-notification-item {{#url}}user-notification-item-clickable{{/url}} {{#isUnread}}user-notification-item-unread{{/isUnread}}">
                        <span class="details">
                            <i class="{{icon}}"></i> {{text}}
                        </span>
                        <div>
                            <span class="notification-time" title="{{time}}">{{timeAgo}}</span>
                            {{#isUnread}}
                            <span> - 
                                <span data-notification-id="{{userNotificationId}}" class="set-as-read-text set-notification-as-read">@L("SetAsRead")</span>
                            </span>
                            {{/isUnread}}
                        </div>
                    </a>
                </li>
                {{/notifications}}
            </ul>
            {{^notifications.length}}
            <div class="notification-empty-text">
                @L("ThereIsNoNotification")
            </div>
            {{/notifications.length}}
        </li>
        {{#notifications.length}}
        <li class="external notifications-footer">
            <div class="text-center"><a href="@Url.Action("Index", "Notifications", new {area = "Mpa"})">@L("SeeAllNotifications")</a></div>
        </li>
        {{/notifications.length}}
    </ul>
</script>

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Views/Layout/_Layout.cshtml
@using System.Threading
@using System.Web.Optimization
@using Abp.Extensions
@using Abp.Timing
@using Abp.Web.Mvc.Extensions
@using MyCompanyName.AbpZeroTemplate.Localization
@using MyCompanyName.AbpZeroTemplate.Web.Bundling
<!DOCTYPE html>
<!--[if IE 8]> <html lang="en" class="ie8 no-js" data-ng-app="app"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js" data-ng-app="app"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" @(CultureHelper.IsRtl ? "dir=\"rtl\"" : "")>
<!--<![endif]-->
<head>
    <title>AbpZeroTemplate</title>
    <meta charset="utf-8" />

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta content="" name="description" />
    <meta content="" name="author" />

    <link rel="shortcut icon" href="~/favicon.ico" />

    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />

    @Styles.Render("~/Bundles/Mpa/libs/css" + (CultureHelper.IsRtl ? "RTL" : ""))
    @Styles.Render("~/Bundles/Mpa/metronic/css" + (CultureHelper.IsRtl ? "RTL" : ""))
    @Styles.Render("~/Bundles/Common/css")

    @Html.IncludeStyle("~/Areas/Mpa/Views/Layout/_Layout.min.css")

    @RenderSection("Styles", false)

    <script type="text/javascript">
        @* This is used to get the application's root path from javascript.
        It's useful if you're running application in a virtual directory under IIS. *@
        var abp = abp || {}; abp.appPath = '@ApplicationPath';
    </script>
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
<!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
<!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
<!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
<!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
<!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
<!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
<body class="page-md page-header-fixed page-sidebar-closed-hide-logo">

    <div class="page-header navbar navbar-fixed-top md-shadow-zero-light">
        @Html.Action("Header", "Layout")
    </div>

    <div class="clearfix">
    </div>

    <div class="page-container">
        <div class="page-sidebar-wrapper">
            @Html.Action("Sidebar", "Layout", new { currentPageName = ViewBag.CurrentPageName })
        </div>
        <div class="page-content-wrapper">
            <div class="page-content">
                @RenderBody()
            </div>
        </div>
    </div>

    <div class="page-footer">
        @Html.Action("Footer", "Layout")
    </div>

    <!--[if lt IE 9]>
        <script src="~/libs/respond/respond.min.js"></script>
        <script src="~/libs/html5shiv/html5shiv.js"></script>
        <script src="~/libs/excanvas/excanvas.min.js"></script>
    <![endif]-->
    @Scripts.Render("~/Bundles/Mpa/libs/js")

    @Html.IncludeScript(ScriptPaths.JQuery_Validation_Localization)
    @Html.IncludeScript(ScriptPaths.JQuery_JTable_Localization)
    @Html.IncludeScript(ScriptPaths.Bootstrap_Select_Localization)

    <script>
        abp.localization.defaultSourceName = '@LocalizationSourceName';
        moment.locale('@Thread.CurrentThread.CurrentUICulture.Name.Left(2)'); //Localizing moment.js
    </script>

    <!-- Dynamic scripts of ABP system (They are created on runtime and can not be bundled) -->
    <script src="~/api/AbpServiceProxies/GetAll"></script>
    <script src="~/AbpScripts/GetScripts?v=@(Clock.Now.Ticks)" type="text/javascript"></script>

    <!-- SignalR scripts -->
    <script src="~/signalr/hubs"></script>
    @Html.IncludeScript("~/Abp/Framework/scripts/libs/abp.signalr.js")

    @Scripts.Render("~/Bundles/Mpa/metronic/js")
    <script type="text/javascript">
        App.setAssetsPath(abp.appPath + 'metronic/assets/');
    </script>

    @Scripts.Render("~/Bundles/Common/js")
    @Scripts.Render("~/Bundles/Mpa/Common/js")

    @Html.IncludeScript("~/Areas/Mpa/Views/Layout/_Header.js")

    @RenderSection("Scripts", false)
</body>
</html>

src/MyCompanyName.AbpZeroTemplate.Web/Areas/Mpa/Views/Layout/_Sidebar.cshtml
@using Abp.Collections.Extensions
@using MyCompanyName.AbpZeroTemplate.Web.Views
@model MyCompanyName.AbpZeroTemplate.Web.Areas.Mpa.Models.Layout.SidebarViewModel
@{
    var calculateMenuUrl = new Func<string, string>((url) =>
    {
        if (string.IsNullOrEmpty(url))
        {
            return ApplicationPath;
        }
        
        if (UrlChecker.IsRooted(url))
        {
            return url;
        }

        return ApplicationPath + url;
    });
}
<div class="page-sidebar navbar-collapse collapse">
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
        @for (var i = 0; i < Model.Menu.Items.Count; i++)
        {
            var menuItem = Model.Menu.Items[i];
            var isActive = Model.CurrentPageName == menuItem.Name ||
                           (!menuItem.Items.IsNullOrEmpty() && menuItem.Items.Any(item => item.Name == Model.CurrentPageName));
            <li class="@(i==0 ? "start" : "") @(isActive ? "active" : "")">
                @if (menuItem.Items.IsNullOrEmpty())
                {
                    <a href="@calculateMenuUrl(menuItem.Url)">
                        <i class="@menuItem.Icon"></i>
                        <span class="title">@menuItem.DisplayName</span>
                    </a>
                }
                else
                {
                    <a href="javascript:;" class="auto">
                        <i class="@menuItem.Icon"></i>
                        <span class="title">@menuItem.DisplayName</span>
                        <span class="arrow"></span>
                    </a>
                    <ul class="sub-menu">
                        @foreach (var childMenuItem in menuItem.Items)
                        {
                            <li class="@(Model.CurrentPageName == childMenuItem.Name ? "active" : "")">
                                @if (childMenuItem.Items.IsNullOrEmpty())
                                {
                                    <a href="@calculateMenuUrl(childMenuItem.Url)">
                                        <span><i class="sub-menu-icon @childMenuItem.Icon"></i> @childMenuItem.DisplayName</span>
                                    </a>
                                }
                                else
                                {
                                    <a href="javascript:;" class="auto">
                                        <i class="@childMenuItem.Icon"></i>
                                        <span class="title">@childMenuItem.DisplayName</span>
                                        <span class="arrow"></span>
                                    </a>
                                    <ul class="sub-menu">
                                        @foreach (var secondLevelChildMenuItem in childMenuItem.Items)
                                        {
                                            <li class="@(Model.CurrentPageName == secondLevelChildMenuItem.Name ? "active" : "")">
                                                <a href="@calculateMenuUrl(secondLevelChildMenuItem.Url)">
                                                    <span><i class="sub-menu-icon @secondLevelChildMenuItem.Icon"></i> @secondLevelChildMenuItem.DisplayName</span>
                                                </a>
                                            </li>
                                        }
                                    </ul>
                                }
                            </li>
                        }
                    </ul>
                }
            </li>
        }
    </ul>

</div>	